dubbo:
  cloud:
    # 指定需要订阅的服务,默认值为*, 会订阅所有服务,不建议使用
    subscribed-services: spring-cloud-dubbo-provide
  protocol:
    name: dubbo
    port: -1

spring:
  application:
    name: spring-cloud-dubbo-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8050